### ISSUE TITLE
illuminate/support issue

### ISSUE THREAD

**Issue by malsgit** [Laralabs/geo-sorter#3]
Hi,

I'm trying to install this via composer, using Laravel 8 & PHP8X and running into the following error

Problem 1
    - laralabs/geo-sorter v2.0.0 requires illuminate/support ^5.5 -> found illuminate/support[v5.5.0, ..., 5.8.x-dev] but these were not loaded, likely because it conflicts with another require.
    - laralabs/geo-sorter v2.0.1 requires illuminate/support ^5.5|^6.0 -> found illuminate/support[v5.5.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires laralabs/geo-sorter ^2.0 -> satisfiable by laralabs/geo-sorter[v2.0.0, v2.0.1].

Any Idea how to resolve it??

**Comment by clnt** [comment]
Hi @WhalesHaveAccents 

Thanks for using my package and apologies for the issues you are facing.

I have not updated this package for Laravel 8/PHP 8 which is the reason for the error you are getting.

If I can find the time tonight I shall look at upgrading the package to support this, however if not tonight I will take a look tomorrow evening.

I will update you via this issue once I have sorted it 👍

Cheers,
Matt

**Comment by clnt** [comment]
Hi @WhalesHaveAccents 

I've just updated the package and tagged version 3.0.1 - decided to take the time to tidy up the code a bit too!

I will close this issue now but feel free to open another if you encounter any issues.

Cheers,
Matt
