### ISSUE TITLE
Support for Laravel 9 and 10

### ISSUE THREAD

**Issue by pwond** [Laralabs/geo-sorter#6]
Hi there, any chance this could be upgraded to support Laravel 9 and 10? Many thanks in advance

**Comment by clnt** [comment]
Hey @pwond 

Yeah sure no problem I shall look at getting it updated this evening.

Cheers!

**Comment by clnt** [comment]
Version 3.0.3 tagged, should now be sorted

**Comment by pwond** [comment]
Much appreciated @clnt , thank you
